- hosts: "localhost"
  vars_files:
          - "secret.yml"
  vars_prompt:
          - name: "num_item"
            prompt: "enter the number of k8sworker nodes"
            private: no
  tasks:
          - name: "launching the instances for k8s multinode setup"
            ec2:
                    zone: "ap-south-1a"
                    wait: yes
                    assign_public_ip: "yes"
                    ec2_access_key: "{{ u }}"
                    ec2_secret_key: "{{ p }}"
                    instance_tags:
                            Name: "{{ item.name }}"
                    count: "{{ item.num }}"
                    image: "ami-04b1ddd35fd71475a"
                    instance_type: "t2.micro"
                    key_name: "hadoop_slave_key"
                    region: "ap-south-1"
                    wait: yes
                    vpc_subnet_id: "subnet-678b820f"
            loop:
                    - { name: 'k8sworker', num: "{{ num_item }}" }
                    - { name: 'k8smaster', num: 1 }
          - name: "refreshing the inventory"
            meta: "refresh_inventory"
          - pause:
                  seconds: 60
- hosts: "tag_Name_k8smaster"
  roles:
          - role: "k8smaster"
- hosts: "tag_Name_k8sworker"
  roles:
          - role: "k8sworker"
